version: '3' 

services:
  php:
    image: php:8.2-fpm
    volumes:
      - './src:/var/www/html'

  composer:
    image: composer
    volumes:
        - .:/src
    command: install

  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - './src:/var/www/html'
      - './docker/nginx/conf.d:/etc/nginx/conf.d'

  mysql:
    image: mysql:8
    environment:
      - MYSQL_ROOT_PASSWORD=root